name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Run Python Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev] || pip install -r requirements.txt
          pip install pre-commit pytest pytest-cov

      - name: Run pre-commit hooks
        run: pre-commit run --all-files

      - name: Run tests with coverage
        run: |
          pytest --cov=src --cov-config=.coveragerc --cov-report=term --cov-report=xml:coverage.xml --cov-fail-under=90

      - name: Upload coverage report
        if: github.ref_name == 'main' || github.ref_name == 'develop' || github.base_ref == 'main' || github.base_ref == 'develop'
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          fail_ci_if_error: false
